### ISSUE TITLE
Card Form on Kanban board missing labels for displayed fields.

### ISSUE THREAD

**Issue by madshaun1984** [XRM-OSS/D365-PowerKanban#87] opened 2021-09-14 20:07 UTC
Is there any way to show the field labels in the boards card view?

Having the data there is great, but without the labels most of the data lacks context.

IE: An "Is Budget Approved" - "toggle" field on the card, results in simply "yes" or "no" being displayed (no context to let the user know what it represents).

![image](https://user-images.githubusercontent.com/432107/133326422-2c974e9b-3106-4df6-a412-b679b584e4ca.png)

Thanks!

**Comment by DigitalFlow** [comment] 2021-09-17 11:57
Hi @madshaun1984,

When you hover over the value, the field name will be shown as tooltip.
Also, depending on where you put your fields inside your card form, they will be rendered differently.
Header and body of the card form don't render their respective field names.

The footer however will display the field names to the side of the value:
![grafik](https://user-images.githubusercontent.com/4287938/133778858-3d905c82-adcf-49e5-81b7-a80e63486c75.png)

Can you try whether this resolves your issue?

Kind regards,
Florian

**Comment by DigitalFlow** [comment] 2021-11-14 23:45
Closing this as no further response was received and rendering is working as intended.

**Closed by DigitalFlow** 2021-11-14 23:45 UTC
